export {default as Navbar} from './navbar/Navbar'
export {default as Main} from './main/Main'
export {default as About} from './about/About'
export {default as Portfolio} from './portfolio/Portfolio'
export {default as Contact} from './contact/Contact'